### PR TITLE
Event clean up

### PR DESCRIPTION
**Pull request by Midhil457**
Cleaned Up some examples

I am separating all the changes into small PRs for easier reviewing. Hoping make more PRs in the coming weeks with more examples cleaned up

**Changed examples: **
AdMob
Lights
move object around position
Level editor
Button
Change position
Create random object
Animation change
Create object with mouse click

You can see the changes made in each example in the commit descriptions
:)

### CODE REVIEW

**Comment by 4ian** [comment]
Nice! Thanks for taking the time to do this 🤩

A few comments:
- I think it would be nice to maybe keep the full AdMob app ids in the example - to have a "real" example and help people be confident that the format of the id is good.
- For `Remove SineMovement behavior and use ToDeg(TimeFromStart()) an "Put object around another"` => not big deal, but I'm trying to encourage more and more game creation trough the usage of custom behaviors. Might be worth keeping the SineMovement, but up to you!

**Comment by Midhil457** [comment]
Thanks for reviewing!

> I think it would be nice to maybe keep the full AdMob app ids in the example - to have a "real" example and help people be confident that the format of the id is good.

that's weird because I never touched the admob ids. I think it might have been done by the engine itself?? Anyways, I pasted the app ids found in the .json file

`<!--StartFragment-->{        "extension": "AdMob",        "property": "AdMobAppIdAndroid",        "value": "ca-app-pub-3940256099942544~3347511713"      },      {        "extension": "AdMob",        "property": "AdMobAppIdIos",        "value": "ca-app-pub-3940256099942544~3347511713"      },      {        "extension": "AdMob2",        "property": "AdMobAppIdAndroid",        "value": "ca-app-pub-3940256099942544~3347511713"      },      {        "extension": "AdMob2",        "property": "AdMobAppIdIos",        "value": "ca-app-pub-3940256099942544~3347511713"      }<!--EndFragment-->`

> For Remove SineMovement behavior and use ToDeg(TimeFromStart()) an "Put object around another" => not big deal, but I'm trying to encourage more and more game creation trough the usage of custom behaviors. Might be worth keeping the SineMovement, but up to you!

About the light example. I remade it. I felt that the existing example didn't showed what's possible with lights, it was just some lights in a scene. I tried showing how lights can be used in games. And made a small game with one level. I tried keeping it simple. All the assets are some the assets store, just resized to make it work great with the lights

:)

**Comment by Bouh** [comment]
# Lights 
Lights example is a technical demo, you have reworked it for a game.
It's not bad but there is no need for a game with mechanics that can hide light possibilities.

I suggest to reduce to a static camera, limit of the screen is the border.
One or two platform move with sine behavior, that show dynamic light. (Sine behavior rather than two objects for check left and right, that use useless sprite btw)
And in a corner add a fix light, and in the other corner a moving light.
Maybe also add a area where when the player go inside the light colors change.
Delete superfluous objects and their resources. 

# Other files
Delete autosave files


Admob keys are ok and come from test key on Google documentation.

**Comment by Midhil457** [comment]
I have made a nessasary changes :)

> I suggest to reduce to a static camera, limit of the screen is the border.

I didn't understand what you mean. Make the camera not move at all or move between rooms? I tried making the camera zoom out and not move at all. But, the lights looked small and hard to navigate. So, I didn't do it

- Also removed all the autosave

- Another mistake I made on my part, I commited an additional 2 more cleaned up projects that where supposed to be for the next PR. I hope this won't be a problem

- Those are
    - Character selection
    -  Change sprite color


:)

**Comment by Midhil457** [comment]
Sorry to disturb, can this be reviewed? so that I can work on the rest of the examples

:)

**Comment by 4ian** [comment]
Sorry for the delay there, I was thinking the PR was not finished :) 

I think it looks good. The lights is a bit more complex, might be worth at some point re-introducing a simpler "light" object example, but this works well.

Thanks a lot for taking the time to do these clean up and improvements! :)

**Comment by Bouh** [comment]
Character selection:
You use Player as group for select a Player1 or Player2 or Player3. Give another name to the group. PlayerGroup?

The light example is cool in terms of gameplay, in terms of polish I prefer the actual light example even if it is less demonstrative.
The goal is to have the functionality not a mini game.
A small game air that fits on a fixed screen with a wall, an object that moves and a candle is largely sufficient.

**Comment by Midhil457** [comment]
> You use Player as group for select a Player1 or Player2 or Player3. Give another name to the group. PlayerGroup?

I will fix this in the next batch of PR

> The light example is cool in terms of gameplay, in terms of polish I prefer the actual light example even if it is less demonstrative.
The goal is to have the functionality not a mini game.
A small game air that fits on a fixed screen with a wall, an object that moves and a candle is largely sufficient.

coincidentally, the first version I made was very similar to this. I might have gone a bit overboard with this example. I will be happy to redo it and make it more functional if you say so

:)

**Comment by 4ian** [comment]
Might be a good idea to simplify a small bit the light example yeah (or make a different example :)).

> I will fix this in the next batch of PR

👍

**Pull request merged**
