### PR TITLE
 Spherez: New game template

### PR DESCRIPTION
**Pull request by tristanbob**
Shoot the blocks before they touch the ground.  Earn extra balls and destroy the blocks by aiming carefully.

This is a game template made with GDevelop, a no-code open-source game engine.

## Play game
https://liluo.io/victrisgames/spherez

## Gameplay video
https://user-images.githubusercontent.com/8879811/179383481-9aa52791-94be-4349-9eaa-960f878a168b.mp4

### CODE REVIEW

**Comment by Bouh** [comment]
The game works like a charm on my low-end phone 👍 
- [ ] There are two `Create Blocks` event groups (one unused)
- [ ] When the game is paused the buttons under can be clicked
- [ ] Try to optimize the readability of events.
For instance from .. to..
image
image
- [ ] Empty event lines, in scene **Main Menu > Buttons > Edit with GDevelop**
- [ ] In same place, you do:
image
To hide the text object you check if the cursor is not on the logo, but this is called every frame, just insert a Trigger Once with it.
When you have doubt you can still add a console log action and see how it performs in the debugger. 
- [ ]  As for the item above, add Trigger Once on other buttons, (leaderboard, pause, play, etc)

Most of the things I spotted are that you can group more events, and you can add more Trigger Once.
But as the performance are nice, it's not a big deal.

It was fun to play, I reach the 17th lvl :)

**Comment by tristanbob** [comment]
@Bouh I think have addressed all the points in your review.  Care to take another look?

https://liluo.io/victrisgames/spherez

**Review by Bouh — APPROVED** [review]

**Comment by Bouh** [comment]
@tristanbob Up to you to click on merge when you think it's fine ;)

**Comment by tristanbob** [comment]
TODO:

- [ ] Remove "advanced bloom" from blocks
- [ ] Find out why balls fall through on title screen within 1 or 2 minutes.  Perhaps the logic to delete balls needs a ForEach()?

**Review by Bouh — APPROVED** [review]

**Pull request merged**
