### PR TITLE
Add Voice recognition example

### PR DESCRIPTION
**Pull request by Bouh**
Close https://github.com/GDevelopApp/GDevelop-examples/issues/322

The extension is already merged in the community list.

### CODE REVIEW

**Comment by ClementPasteau** [comment]
@Bouh the example does not seem to work for me with an error
image

**Comment by Bouh** [comment]
> @Bouh the example does not seem to work for me with an error image

@planktonfun the extension have an issue when the speech ends.

**Comment by planktonfun** [comment]
I saw the problem, how do I send a fix here?

**Comment by Bouh** [comment]
> @Bouh I saw the problem, how do I send a fix here?

If you can't push a commit on the branch **Add_new_example_VoiceRecognition** just send here a zip file with the extension only, then I'll add the commit.

**Comment by planktonfun** [comment]
> If you can't push a commit on the branch Add_new_example_VoiceRecognition just send here a zip file with the extension only, then I'll add the commit.

Extension file: [VoiceRecognition.json.zip](https://github.com/GDevelopApp/GDevelop-examples/files/9165376/VoiceRecognition.json.zip)

**Comment by Bouh** [comment]
> > If you can't push a commit on the branch Add_new_example_VoiceRecognition just send here a zip file with the extension only, then I'll add the commit.
> 
> Extension file: [VoiceRecognition.json.zip](https://github.com/GDevelopApp/GDevelop-examples/files/9165376/VoiceRecognition.json.zip)

image

😎

Extension and example have been commited.
Ready for a last review.

**Review by D8H — APPROVED** [review]
It's working for me too.

image

**Pull request merged**
