### PR TITLE
Swapping camera extension and fixing animations for the platformer example

### PR DESCRIPTION
**Pull request by HelperWesley**
Changes to the platformer example include:

-Removing the "simple smooth camera" extension.
-Adding the "smooth camera" extension.
-Removing the player start object.(Not needed)
-Changing the first checkpoint to be where the player object is at beginning of scene.
-Swapping the broken climb animation in the platformer example to the fixed version of the animation that was in the asset store.

### CODE REVIEW

**Comment by tristanbob** [comment]
@HelperWesley Can you provide a Liluo link of this version for testing?

**Comment by D8H** [comment]
> @HelperWesley Can you provide a Liluo link of this version for testing?

https://games.gdevelop-app.com/game-512cba9c-29c5-49b0-b9eb-76aad9602e03/index.html

**Comment by tristanbob** [comment]
> > @HelperWesley Can you provide a Liluo link of this version for testing?
> 
> https://games.gdevelop-app.com/game-512cba9c-29c5-49b0-b9eb-76aad9602e03/index.html

Thanks @D8H .  We need to roll back the changes to the boundaries. 

1) The player should not leave the screen.  
2) If the boundaries are not exactly lined up square, it bothers me.  :)

**Comment by HelperWesley** [comment]
@tristanbob Nothing was done to the boundaries, the camera not going up was because of the camera controls we set to not go in the Y direction.

That's been changed in the most recent commit. It doesn't line up with the video perfectly any more, but there's a lot in the finished game that didn't make it in to the video. Sooooo. 🤷‍♂️

**Pull request merged**
