### PR TITLE
Add Turn Based Fighting example by shadow00dev

### PR DESCRIPTION
**Pull request by Midhil457**
### Description
A simple turn based fighting game where the player battles with a bot.

The example works on mobile and desktop.Uses assets from kenney.nl and pzUH. The sound effects are made using bfxr and chrome music lab.

### Details
Authors: shadow00dev 
Submission issue: #121

thumbnail

### CODE REVIEW

**Comment by shadow00dev** [comment]
the start menu has a bug with starting the game(I don't remember that bug being in my version lol)

**Comment by Midhil457** [comment]
Fixed it, I didn't update the scene name in the events

**Comment by shadow00dev** [comment]
> Fixed it, I didn't update the scene name in the events

thanks

**Comment by Midhil457** [comment]
Also fixed menu being small on desktop

**Comment by Midhil457** [comment]
Merging this :)

**Comment by shadow00dev** [comment]
:) thanks

**Pull request merged**
