### PR TITLE
Asteroids example

### PR DESCRIPTION
**Pull request by ddabrahim**
Update the Asteroids example to comply with the latest guidelines and best practices.

Variables declared in variables editor
Timers started before use
Replaced the end game timer with the new wait event, more practical.
Audio files added to resources, at the same time removed the event hack used to preload them, they should be preloaded now along with all the other resources.
Added a preview image also.

Fixed audio playback in Safari/iPhone/iPad replaced .ogg with .mp3 files and made sure to preload audio as sound.

Added missing colliders to ship and asteroids to improve accuracy of collision checking.

Ready to merge.

### CODE REVIEW

**Comment by D8H** [comment]
### Preview the game(s) changed or added in this Pull Request

* https://editor.gdevelop.io?project=https://raw.githubusercontent.com/ddabrahim/GDevelop-examples/Asteroids-example/examples/asteroids/asteroids.json

**Comment by D8H** [comment]
Thank you for updating this example.

I did a few changes:
- Add a comment to redirect users to a similar example with simpler events:
  https://gdevelop.io/game-example/free/space-asteroids
- Remove the thumbnail to avoid to put more light to this example.
- Revert the audio conversion as wav files are too heavy.
  - AAC in mp4 could be a solution, but I think it's fine too keep the ogg.

Let me know when the PR should be merged.

**Comment by ddabrahim** [comment]
@D8H May I ask why did you reverse the audio playback fix? Without this fix the example does not work properly on iPhone and iPad version of GDevelop and inside Safari web browser.

Also what is wrong with the preview image?

**Comment by D8H** [comment]
> May I ask why did you reverse the audio playback fix?

I thought only the files were changed. I put the flags back.

> Also what is wrong with the preview image?

The thumbnail is fine, but examples with a thumbnail are shown on the top of the example list.

> I can also see you added a warning regarding the example is outdated. The purpose of this PR is to update it.

This is to redirect users to a similar examples with 3 times shorter events and nice assets.

**Comment by ddabrahim** [comment]
@D8H I agree that wav was a bit heavy but sadly ogg does not seem to work on iPhone, iPad and inside Safari. Maybe more examples are broken on iPhone and iPad then realised. Maybe worth to check.

As my final commit, I have added missing colliders to ship and asteroids to improve accuracy of collision checking and made an other attempt to fix Audio playback using mp3 sounds this time instead of wav.

If it's all good with you and tests are not failing, it is ready to merge on my part.

Thanks.

**Pull request merged**
