### PR TITLE
Rework example for stickman hook Starter

### PR DESCRIPTION
**Pull request by ClementPasteau**
Screenshot 2022-04-25 at 18 50 12

Game link: https://liluo.io/games/ee1a52e9-5f0a-49e0-bcbf-940cee1a637b

[stickman-hook.zip](https://github.com/GDevelopApp/GDevelop-examples/files/8563875/stickman-hook.zip)

### CODE REVIEW

**Comment by Midhil457** [comment]
Here is my short review :)

- Instead of creating the Ending UI using events when needed,It would be easier to show a layer with the Ending UI when the player finishes.
End

- `Add` 1 instead
Add1

- There are some empty events
- Instead of a timer, `TimeFromStart()` expression could be used

- The example is given many names `Grab the stars` [Menu], `Stickman hook` [Project name], `Bounce And Hook` [package name. Maybe we should **stick** to one [haha]. `Bounce and hook` conveys the theme well

**Comment by ClementPasteau** [comment]
Thanks for the feedback!

I've cleaned up the events + renamed the project to be consistent.

published here too: https://liluo.io/clem/bounce-and-hook

image

**Comment by Midhil457** [comment]
Good to go ig. No issues found from my side

**Comment by ClementPasteau** [comment]
Thanks for the review @Midhil457 !

**Pull request merged**
