### PR TITLE
New leaderboard example (Highscore and Speedrun modes)

### PR DESCRIPTION
**Pull request by tristanbob**
## Changes ##
- Move the existing Firebase leaderboard example from "leaderboards" to "leaderboards-firebase".
- Demonstrates how to use the new leaderboards provided by GDevelop
- Includes two types of mini-games: Highscore and Speedrun

**Note:** This PR moves the existing leaderboards example to a new directory, with the goal of making it easier for people to find this new example.  If this will cause any problems, this change will need to be modified.

## Playable game ##

https://liluo.io/victrisgames/leaderboard

## Video ## 

https://user-images.githubusercontent.com/8879811/170809828-6889e522-66e2-45d4-a123-0d78529d9c42.mp4

### CODE REVIEW

**Comment by 4ian** [comment]
LGTM!

**Comment by Bouh** [comment]
Wait I do a review and I make changes right now. I'll merge after.

**Review by Bouh — APPROVED** [review]
Feel free to merge when you want

In my commit message I miss to add one line:
- I generated the player name before submitting it to the leaderboard this way the user can see the placeholder with a random name "Player6519" and this name is visible on the leaderboard.
Compared to before there was no name if not filled before, and it was impossible to know who is who on the leaderboard.

**Comment by tristanbob** [comment]
> Feel free to merge when you want
> 
> In my commit message I miss to add one line:
> 
> * I generated the player name before submitting it to the leaderboard this way the user can see the placeholder with a random name "Player6519" and this name is visible on the leaderboard.
>   Compared to before there was no name if not filled before, and it was impossible to know who is who on the leaderboard.

Thanks for this great feedback and improvements!  I love the countdown (my daughter said it needed to be there).

I'll merge this now.

**Pull request merged**
