### PR TITLE
Add a card system example

### PR DESCRIPTION
**Pull request by D8H**
## Card System Example

Show how to use the "Object Stack" extension to make a card system.

* Short video: https://user-images.githubusercontent.com/2611977/133291953-b2f49035-17eb-472d-902e-8594d7a2555b.mp4
* Build: https://d8h.itch.io/card-system-demo
* Project: https://www.dropbox.com/s/t7ltigvjzvgq4k6/card-system.zip?dl=1

CardExample

## Checklist

 * [x]  My game has a proper name in the game properties.
 * [x]  My game package name behind with `com.example.`.
 * [x]  My game has all events unfolded.
 * [x]  I've added myself as the author in the game properties.
 * [x]  I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
 * [x]  I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
 * [x]  I've cleaned unused resources.

### CODE REVIEW

**Comment by Bouh** [comment]
Lgtm

**Review by Bouh — APPROVED** [review]

**Comment by Midhil457** [comment]
Hi,
- The project uses `Point inside object` instead of ` cursor on object`. Is there a reason for this? `Cursor on object` is more preferred.
- Maybe add a comment on top saying that this example is an example project for the Card extension

-The package name needs to be `com.gdexample.<project name>`. The format was recently changed so that the examples don't accidentally conflict with the games made by users (Which have `com.example` as default) and also to be able to differentiate the examples

:)

**Comment by 4ian** [comment]
> The package name needs to be com.gdexample.<project name>. The format was recently changed so that the examples don't accidentally conflict with the games made by users (Which have com.example as default) and also to be able to differentiate the examples

I'm not sure if we should keep this mandatory - `com.example` already has a warning in the app telling you that you must change and will be rejected by app stores anyway, so it seems safer to use these rather than risking someone using com.gdexample for a real game - which will happen sooner or later.

**Comment by 4ian** [comment]
I went ahead and merged this so that we don't forget this - the remaining points were not blocking compared to having this nice example :)

**Pull request merged**
