### PR TITLE
Update Project Properties (Author names updated)

### PR DESCRIPTION
**Pull request by Midhil457**
- Updated the author names (new usernames). The list of author names that are changed with the example name is listed at the end of the post. The rest don't have a username
- Updated Project name
- Updated package name to start with `com.gdexample`. This was done so that the example could be differentiated from the games made by users without a proper package name

List of author names changed (Only the examples that had a author is included in this list)

If your name is not updated (see list below). Please register a username and create an issue here or commit to this PR with your author name updated i your examples ;)

✅️ - Author updated
⛔️ - Username not found/author not updated

not-a-vania: Silver-Streak ✅️
cannon-ball-with-physics: The Gem Dev ✅️
menu-with-functions-and-text-effects: Phenomena ⛔️
geometry-monster: mypoint13k ⛔️
z-depth: gametemplates.itch.io ✅️
particle-effects-demo: Wishforge Games ⛔️
breakout: Midhil M(Leo Red) ✅️
reflective-surface: VegeTato ⛔️
procedural-generation: Add00 ✅️
shootalia-top-down-shooter: Ulises Freitas <ulises.freitas@gmail.com> ⛔️
level-selection-unlock: ddabrahim gametemplates.itch.io ✅️
marching-squares-liquids: D8H ✅️
marching-squares-fog-of-war: D8H ✅️
magnet: Entropy ✅️
video-player: Bouh ✅️
screen-shake: Zat ⛔️
snap-object-to-grid: Lizard-13 ⛔️ , D8H ✅️
tic-tac-toe: Jurfix (Yaroslav Nazarenko) ⛔️
lights: Midhil M (Leo Red) ✅️
tetris-demo: codequest ⛔️
space-invaders: Zat ⛔️
isometric-game: Mickael HOARAU ⛔️
layer-effects: The Gem Dev ✅️
multi-language-menu: gametemplates.itch.io ddabrahim ✅️
inventory-system: ddabrahim ✅️
bomb-the-crate: Victor Angelo V. Enriquez ⛔️
rain: CROSS  ⛔️
yarnalia: Ulises Freitas ⛔️
minesweeper: Tristan Rhodes ✅️, Alaska ⛔️, Bouh ✅️, Leo-Red ✅️
ping-pong: Leo Red (Midhil M) ✅️
tactical-game-grid-movement: D8H ✅️
city-builder: D8H ✅️
virtual-joystick: Leo Red (Midhil M) ✅️
multiplayer-platformer-with-gamepads: Bouh ✅️
platformer-mystery-box: GameForGaming ⛔️
downhill-bike-physics-demo: Zat ⛔️
dialogue-tree-with-yarn: Todor Imreorov aka blurymind ⛔️
geodash: Zat ⛔️
top-down-adventure-camera: Silver-Streak ✅️
firebase-example: Arthur Pacaud (arthuro555) ✅️
stick-objects: D8H ✅️
text-entry-object: ddabrahim ✅️ /Greench ⛔️ 
leaderboards: Arthur Pacaud (arthuro555) ✅️
board-walk-with-raycast: Paulo Amaral
parse-json-from-api: gametemplates.itch.io ✅️
reset-checkpoints: Elairyx ✅️
create-random-object: ddabrahim gametemplates.itch.io ✅️
spatial-sound: Arthur Pacaud (arthuro555) ✅️
random-number-or-string-from-a-list: Ulises Freitas ⛔️
forward-camera: Lounès ⛔️
facebook-instant-game: Bouh ✅️
bim-bam: D8H ✅️
random-points-in-area: hawkbyte ⛔️
p2p-networking: Arthur Pacaud (arthuro555) ✅️
platformer-ai: Mrtubagames ⛔️
game-feel-demo: Sleeper_Games ⛔️
titan-souls-demo: HelperWesley ✅️
bouncing-ball-and-rope: Zatapov ⛔️
rectangular-movement: Tristan Rhodes (https://victrisgames.itch.io/) ✅️
flappy-bird: THE GEM TUTORIALS ✅️
car-physics: frolics2dio ✅️
rhythm: Ulises Freitas ⛔️
menu-with-tweens: Dreamkingmovies ⛔️
dungeon-generator: Tristan Rhodes ✅️

### CODE REVIEW

**Comment by 4ian** [comment]
Incredible work!! 
There is a conflict because of changes you made in https://github.com/GDevelopApp/GDevelop-examples/pull/122 I think, see if you can solve this? Let me know if you're blocked. Once this is fixed we can merge this batch of authors! :D

**Comment by Midhil457** [comment]
I think I resolved it

**Comment by 4ian** [comment]
Thank you!

**Comment by arthuro555** [comment]
🚀

**Pull request merged**
