### PR TITLE
New example: Random points with min and max distance

### PR DESCRIPTION
**Pull request by LeopoldTal**
Demonstrates how to generate points within a square, circle, and ring (annulus) between two circles.

- [X] Game name ("Random points with min and max distance")
- [X] Author name ("hawkbyte")
- [X] Package name ("com.example.areasampling")
- [X] README
- [x] Thumbnail
- [X] All events unfolded
- [X] Resources cleaned up

### CODE REVIEW

**Comment by Midhil457** [comment]
Hi, 

- You should be putting the project inside the example folder, not in the root folder
- If I am correct, the example's name is taken from the json file. So, it might be a good idea to change the json file's name to the project's name
- It would be great if you could shorten the example's name as the long name is causing some texts to overflow in some parts of the GUI, it would also make it search friendly

:)

**Review by Midhil457 — CHANGES_REQUESTED** [review]
Remove the old folder from root folder

**Comment by LeopoldTal** [comment]
> Remove the old folder from root folder

Hm? That's already done. Try `git clean -d`?

**Comment by Midhil457** [comment]
> Hm? That's already done. Try git clean -d?

I guess it was my issues, that folder doesn't seem to exist in the branch

- I saw the thumbnail, and I am not sure if I am correct. but, picture as big as 420x420 might not be required. The platformer example seems to have a thumbnail thats 64x64. Sorry that I didn't mention it in the first review 😅

**Review by Midhil457 — APPROVED** [review]
Looks good to go

:)

**Comment by 4ian** [comment]
Merged! Thanks both 👍👍

**Pull request merged**
