### PR TITLE
Add Platformer Room Camera

### PR DESCRIPTION
**Pull request by Midhil457**
### Description
This example shows hows to move camera in between rooms using tweens.

In this example, the camera will smoothly move into the next room when the player leaves it in any of the cardinal directions. The examples also has the additions that the player will get an additional jump when jumping up into a transition and will be kept within the current frame when the transition is in progress.

### Details
Author: Elairyx7301
Submission: #149

139862428-0ce20b40-6c53-4730-8e7d-1389caf9a8a9

### CODE REVIEW

**Comment by 4ian** [comment]
I see you did a review already, so happy for you to merge this!

**Comment by 4ian** [comment]
I've just tried the example and it's lagging a bit (~20-30 fps) on my computer, which is weird. Is this also the case for you?

**Comment by Midhil457** [comment]
> I've just tried the example and it's lagging a bit (~20-30 fps) on my computer, which is weird. Is this also the case for you?

I did have some lagging issue on another older computer, but thought it might be bacause it was a 32-bit device. But, I didn't experience any major issue s on my regular computer

I have cut down on coins and removed the effects from them to try fixing it, And also set the max fps to 0 (Not that I think removing the max fps will fix the issue) could you test it out now?

**Comment by 4ian** [comment]
Running well - not sure if it was an overload of something or just my computer.
Looks great then, good to go 👍 I let you squash and merge? Don't forget to set a title like "Add Platformer Room Camera example (thanks Elairyx7301)", as the commit title (and description) is going to the changelog :) 

image

image

**Comment by Midhil457** [comment]
Thanks for letting me merge! Merged successfully!

**Pull request merged**
