### PR TITLE
Replace old by new platformer

### PR DESCRIPTION
**Pull request by Bouh**
Past platformer is now called "old-platformer"

Close https://github.com/GDevelopApp/GDevelop-examples/issues/223

### CODE REVIEW

**Comment by 4ian** [comment]
Great! Run `npm run build -- --gdevelop-root-path ...` then `npm run check-post-build -- -u` to update the post-build tests (and/or update manually).

We'll replace the old example, we usually don't do this but I think this is fine because any link will point to the new example and the asset store is not impacted.

**Comment by Bouh** [comment]
I can't build, there is too much errors from old examples, some of them are not updated with recent change made for liluo, playableDevices, categories, description, etc.

A tiny representation of the errors.
```
Child categories not found in SerializerElement::GetChild
Child playableDevices not found in SerializerElement::GetChild
Bool attribute "useDeprecatedZeroAsDefaultZOrder" not found, returning 0Child group not found in SerializerElement::GetChild
Child group not found in SerializerElement::GetChild
Child group not found in SerializerElement::GetChild
Child description not found in SerializerElement::GetChild
Child categories not found in SerializerElement::GetChild
Child playableDevices not found in SerializerElement::GetChild
Bool attribute "useDeprecatedZeroAsDefaultZOrder" not found, returning 0Child description not found in SerializerElement::GetChild
Bool attribute "useDeprecatedZeroAsDefaultZOrder" not found, returning 0Child description not found in SerializerElement::GetChild
Child categories not found in SerializerElement::GetChild
Child playableDevices not found in SerializerElement::GetChild
Bool attribute "useDeprecatedZeroAsDefaultZOrder" not found, returning 0Child description not found in SerializerElement::GetChild
Child categories not found in SerializerElement::GetChild
Child playableDevices not found in SerializerElement::GetChild
Bool attribute "useDeprecatedZeroAsDefaultZOrder" not found, returning 0Child description not found in SerializerElement::GetChild
Child categories not found in SerializerElement::GetChild
Child playableDevices not found in SerializerElement::GetChild
Child description not found in SerializerElement::GetChild
```

**Comment by Bouh** [comment]
Wesley and I have reviewed this example.

We can merge this if you agree.

**Comment by 4ian** [comment]
The preview image was missing, I just added one :)

**Pull request merged**
