### PR TITLE
Add a preview image for asteroid example

### PR DESCRIPTION
**Pull request by Bouh**

### CODE REVIEW

**Comment by Bouh** [comment]
Let me know @AlexandreSi @4ian @ClementPasteau if something else is required to add the **space asteroids** example as starter in top of the homepage!

**Comment by ClementPasteau** [comment]
I think that's all that's needed! I'll double check tomorrow morning

**Comment by 4ian** [comment]
Yay Space Asteroids 😄👍
I wonder if we can have a link in the README to the tutorial?

**Comment by Bouh** [comment]
> Yay Space Asteroids 😄👍
> I wonder if we can have a link in the README to the tutorial?

Even both! What you think of:

--------

Juicy remake of the classic asteroids game using the physics 2.0 behavior.

Watch ours both tutorials to reproduce this game example:
- Part1: [The basics of physics and behavior.](https://www.youtube.com/watch?v=w1SCpQ-mRCk)
- Part2: [Adding game juice with particles, sound effects, screen shake, and everything that makes a game feel good to play.](https://www.youtube.com/watch?v=z3C89rEp6YA)

**Comment by ClementPasteau** [comment]
lgtm, I'd just change your second sentence to: `Watch our tutorials to learn how to recreate this game"

**Pull request merged**
