### PR TITLE
Newgrounds API extension example

### PR DESCRIPTION
**Pull request by planktonfun**
## Describe the example

A demo on how to use newgrounds api extension

## Checklist

- [x] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example).
- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

### CODE REVIEW

**Review by Bouh — CHANGES_REQUESTED** [review]
- [ ] `NewSprite-1.png` is missing in the resources.
image

- [ ] The first event line can be deleted.
image

- [ ] One important thing is to rename the `game.json` with the name of the folder.
`game.json` -> `newgrounds-api.json`

And only if you wish, you can show a thumbnail in the example list by adding a thumbnail.png file next of the game.json, this image need to be a 16:9 ratio and a png file.

**Comment by planktonfun** [comment]
Updated files:

> * [x]  I had trouble loading `NewSprite-1.png`, this file is not present in the folder.
>   image
> * [x]  It seems there are 4 unused objects?

Removed unused objects and assets 

> * [x]  The first event line can be deleted.
>   image

Rearranged and compressed events

> * [x]  One important thing is to rename the `game.json` with the name of the folder.
>   `game.json` -> `newgrounds-api.json`
> 
> * [x] And only if you wish, you can show a thumbnail in the example list by adding a thumbnail.png file next of the game.json, this image need to be a 16:9 ratio and a png file.

Added thumbnail and renamed game file

**Comment by planktonfun** [comment]
@Bouh something weird happened to the auto builder: 
image

**Comment by 4ian** [comment]
The bot showing an automated link to try the example is bugged - don't worry about this, it should not prevent your example to be accepted if @Bouh/other reviewers are fine with it :)

**Review by Bouh — APPROVED** [review]

**Pull request merged**
