### PR TITLE
Clean resources on examples

### PR DESCRIPTION
**Pull request by Bouh**
Continuity of https://github.com/4ian/GDevelop/pull/2713

- [x] Wait until the other PR is merged to merge this one.

Can I have permission and access to this repository, please?

----

Starters examples:

- [x] Platformer
- [x] Space shooter
- [x] Geometry monster
- [x] Isometric game
- [x] Downhill bike physics demo
- [x] Pairs
- [x] Particle effects demo
- [x] Game feel demo

All examples to check: 

- [x] Center object within another
- [x] Change position of object
- [x] Change scale of sprites
- [x] Change sprite color
- [x] Count down timer
- [x] Create object with mouseclick
- [x] Custom font
- [x] Custom mouse pointer
- [x] Customize keys with lastpressedkey
- [x] Exit app
- [x] Load image from url
- [x] Move object in circle
- [x] Multitouch
- [x] Open url in browser
- [x] Parse json string
- [x] Particles explosions
- [x] Play music on mobile
- [x] Rotate toward position
- [x] Rotate with keypress
- [x] Snap object to grid
- [x] Splash screen
- [x] Text entry object
- [x] Text to speech
- [x] Device orientation compass
- [x] Device vibration
- [x] Infinite scrolling background
- [x] Rotate toward mouse
- [x] Shoot bullets
- [x] Take screenshot
- [x] Bbtext object demo
- [x] Create random object
- [x] Lights
- [x] Manipulate text object
- [x] Move camera to position
- [x] Move object back and forth
- [x] Move object toward position
- [x] Move object with mouse joint
- [x] Move object with physics
- [x] Object gravity
- [x] Object selection
- [x] Objects timers
- [x] Parallax
- [x] Parse json from api
- [x] Particles various effects
- [x] Pathfinding basics
- [x] Pin object to another
- [x] Platformer with tilemap
- [x] Rain
- [x] Shoot bullet in parabola
- [x] Shooting bullets explanation
- [x] Sprite fade in out
- [x] Text fade in out
- [x] Change sprite animation
- [x] Device orientation ballgame
- [x] Play stop sprite animation
- [x] Type on text effect
- [x] Pixel perfect platform game
- [x] Bitmap text
- [x] Board walk with raycast
- [x] Buttons
- [x] Car physics
- [x] Dialogue tree simple demo
- [x] Magnet
- [x] Pin object to another multiple parents
- [x] Plane and clouds
- [x] Tween animations
- [x] Unlock items
- [x] Cannon ball with physics
- [x] Basic artificial intelligence
- [x] Basic ai with pathfinding
- [x] Bouncing ball and rope
- [x] Facebook instant game
- [x] Filesystem create directory
- [x] Random color picker
- [x] Screen shake
- [x] Toggle music play sound
- [x] Menu with functions and text effects
- [x] Save load
- [x] Drag camera with mouse
- [x] Find diagonals
- [x] Multi language menu
- [x] Pathfinding
- [x] Advanced shape based painter
- [x] Physics
- [x] Procedural generation
- [x] Ragdoll
- [x] Bomb the crate
- [x] Parallax scrolling
- [x] Spatial sound
- [x] Drop collect items from storage
- [x] Basic topdown car driving
- [x] Animation speed scale
- [x] Zombie laser
- [x] P2p networking
- [x] Admob
- [x] Simple space shooter
- [x] Tabbed menu with layers
- [x] Keyboard practice
- [x] Level editor
- [x] Z depth
- [x] Tween test
- [x] Level selection unlock
- [x] Javascript blocks in platformer
- [x] Menu with tweens
- [x] Platformer double jump
- [x] Flappy bird
- [x] Health bar
- [x] Physics joints demo
- [x] Character selection
- [x] Endless up runner
- [x] Tilemaps made with tiled editor
- [x] Inventory system
- [x] Video player
- [x] Space invaders
- [x] Breakout
- [x] Geodash
- [x] Titan souls demo
- [x] Firebase example
- [x] Racing game
- [x] Multiplayer platformer with gamepads
- [x] Asteroids
- [x] Tactical game grid movement
- [x] Betabox basics learning experience
- [x] Dialogue tree with yarn
- [x] Physics joints settings demo
- [x] Bim bam
- [x] Goose bomberman
- [x] Layer effects
- [x] Tetris demo

### CODE REVIEW

**Comment by Bouh** [comment]
I'm done!
45 Example edited
92 Examples untouched
137 Total of examples 

All examples edited have a commit log.

Most of them include:
- z ordering on the new option
- clean unused resources
- fix events
- clean empty events
- project files option from multiple to a single file

My process was:
- Compile GD5 with current master once
- Open an example from the new dialog
- Wait for the complete download the project example
- Note all missing resources
- Check if the resources have an impact in game
- If no delete unused resources
- If yes replace or fix files and objects
- Check the game settings, z ordering and package name
- Save as the project

**Comment by Bouh** [comment]
As the serialization is enabled on object for future effects there is a new value on the edited projects, I hope this will not have an influence 😬

**Comment by 4ian** [comment]
> As the serialization is enabled on object for future effects there is a new value on the edited projects, I hope this will not have an influence 😬

No that's great! :)

> My process was:

Awesome! 👍 Thanks for taking the time to do all of that :)

**Comment by 4ian** [comment]
Merged! Thanks again, that's super great :) 

The update is almost instant (~5 minutes for the automatic build and deployment), but the cloudflare cache means that some updates might not be seen before a few hours.

**Comment by Bouh** [comment]
OK, I'll try to clear my cache tonight, and tomorrow I'll download all examples again from the interface and make corrections if needed.

**Pull request merged**
