### PR TITLE
A QIX like game.

### PR DESCRIPTION
**Pull request by D8H**
## Describe the example

Show how to use the "Marching Squares" extension to paint territories.

## Checklist

- [x] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example).
- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

## Game build
* https://d8h.itch.io/quick-impulse-xpansion

### CODE REVIEW

**Comment by 4ian** [comment]
That's super fun 😄

**Review by Midhil457 — CHANGES_REQUESTED** [review]
Here is my review:
- I think it should be `expansion` and not `xpansion`
- The package name can be `com.example.QuickImpulseExpansion`

You can find the other points here (Though there isn't many):
[marching-squares-qix-review.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7668377/marching-squares-qix-review.zip)

:)

**Comment by D8H** [comment]
Thanks for the review.

>   * I think it should be `expansion` and not `xpansion`
>   * The package name can be `com.example.QuickImpulseExpansion`

Actually, this is not a typo. It's to make the initials Q.I.X. like the arcade game.
* https://en.wikipedia.org/wiki/Qix

> You can find the other points here (Though there isn't many): [marching-squares-qix-review.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7668377/marching-squares-qix-review.zip)

I found 3 annotations and made the changes. Did I found every one of them?

**Comment by 4ian** [comment]
Thanks @Midhil457 for checking and @D8H for doing the changes for the annotations. I think this is good to go, no need to wait more!

**Pull request merged**
