### PR TITLE
New game game example: Parking Jam 

### PR DESCRIPTION
**Pull request by tristanbob**
## Description

- Swipe cars into the road to clear the parking lot.  
- Relieve stress by crashing the cars into each other.
- Enable speedrun mode to compete on the leaderboard!

## Event structure

I structured the events in this game differently than usual.  This game has most events inside an External Event called GameLogic.  Each scene is simply a layout of objects that references that external GameLogic event.  

Ok then, why didn't I simply use external layouts instead scenes?  I could have done this, but that would not make it easy to add custom logic for each scene, such as the tutorial in Level 1. 

I think this event structure works well for this game, but let me know if you have ideas/suggestions on how it can be improved.

## Notes to reviewers

- Enable the RED "debugging" event group if you want to right-click through the levels for testing
- Do you like the Title text bouncing "DVD style" or the previous horizontal movement?
- If you drag a car with the mouse outside the game window, your next drag will not work until the mouse is released inside the game window.  I updated the Draggable Physics extension to release the drag when (outside the window AND mouse pressed), but this problem still exists.  If/When @D8H has time, I'd love some help with this.  This defect is not present on full screen touchscreen devices (probably because the cursor can't leave the game window).

## Playable game

https://liluo.io/victrisgames/parking-jam

## Video

https://user-images.githubusercontent.com/8879811/170850617-a1afa623-461c-434c-b44a-dcb2d97b0ab9.mp4

### CODE REVIEW

**Comment by Bouh** [comment]
- [x] DVD style for the title is funny I made a new logo for it! 
image
- I made a new thumbnail with the logo
- I disabled the draggable behavior in level 5 to reduce the CPU usage.
- Add the package name
- Add GDevelop author
- Replace the red laser by a white line, to look like more to a parking slot

**Comment by Bouh** [comment]
Oh I see something wrong with the score in [the game on Liluo.io](https://liluo.io/victrisgames/parking-jam), by default you display 123, and the value isn't refreshing correctly when we start a new level.

**Review by Bouh — COMMENTED** [review]
Lgtm, just fix the score, see my previous comment.

**Comment by tristanbob** [comment]
@Bouh  I just pushed commits to Parking Jam PR.  Remaining items:

- Review my changes
- Update thumbnail?
- Decide if we want to wait for next GDevelop release to publish (dragging out of game window bug)

**Comment by Bouh** [comment]
I made few edits:

- Disable unused behavior for the main scene for performance on mobile
- Remove duplicated instance on scene
- Apply the same purple color in replacement of the blue

I spotted one bug, finish a level, and click on the pause button on top instead of Next level.

**Comment by tristanbob** [comment]
Parking Jam changes:

- Allowed leaderboard to be submitted even if speedrun was disabled
- Added buttons to Level 5 (instead of just text)
- Increased outline around Level text

**Review by Bouh — APPROVED** [review]
👍 🚀

**Comment by tristanbob** [comment]
I tested the pre-release version of GDevelop and it fixes the "dragging outside the game window" bug. 

Parking Jam is merged!!!  :)

**Pull request merged**
