### PR TITLE
Changed Flappy Bird to Tappy Planes

### PR DESCRIPTION
**Pull request by HelperWesley**
Swapped out all of the art assets to Kenney's CC0 1.0 Universal "Tappy Plane" assets, and made new sound assets.

And also:
-Fixed the opening scene transition.
-Added a leaderboard.
-Changed how the gameover screen is displayed.(It's now a prebuilt menu on a layer)

### CODE REVIEW

**Comment by Bouh** [comment]
The test is ok, but the build is not, which is I presume not a problem because the files are correctly added and named.
@ClementPasteau I'm right?

**Comment by ClementPasteau** [comment]
@Bouh those are the errors of the build:
image

Are those images present?

**Comment by Bouh** [comment]
> @Bouh those are the errors of the build: image
> 
> Are those images present?

Yes
image

**Comment by 4ian** [comment]
There was:
- An error in the casing of Thumbnail.png resource
- preview.png was a resource pointing to a non existing file, I removed it.
- The Liluo thumbnail was set to preview.png, I set it to be thumbnail.png

**Review by 4ian — APPROVED** [review]
Ready to go when you are

**Pull request merged**
