### PR TITLE
Top-down terraforming and physics.

### PR DESCRIPTION
**Pull request by D8H**
## Describe the example

Show how to use the "Marching Squares" extension to give a feeling of relief from a top-down viewpoint.

## Checklist

- [x] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example).
- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

## Game build
* https://d8h.itch.io/marching-squares-terraforming

### CODE REVIEW

**Comment by Midhil457** [comment]
Nice project:
- In the README, `relief` also means `a feeling of reassurance and relaxation following release from anxiety or distress` and it might be confusing. maybe change it.
- It would be great if the example gave a link to a wiki page that explains how marching squares extension works (If any) and how the examples itself works . I think it would be great
- The example's name is `SandGolf` but it isn't a complete golf game. So, maybe rename it to `terraforming`
- I wasn't able to find any notable issues with the events, so that's good

**Comment by D8H** [comment]
>     * In the README, `relief` also means `a feeling of reassurance and relaxation following release from anxiety or distress` and it might be confusing. maybe change it.

Would "an impression of relief" work?

>     * It would be great if the example gave a link to a wiki page that explains how marching squares extension works (If any) and how the examples itself works . I think it would be great

The help button already give access to this page.
* https://wiki.gdevelop.io/gdevelop5/all-features/extensions/marching-squares

Capture d’écran 2021-12-07 202600

I understand that it might not be known by everyone but if the page were to move I would rather not having to update every examples.

>     * The example's name is `SandGolf` but it isn't a complete golf game. So, maybe rename it to `terraforming`

This is the scene name and it's not very important as people don't rely on it to browse the examples. This is a pun about "sand box". The example name comes from the folder which is "Marching Squares Terraforming".

**Comment by Midhil457** [comment]
> Would "an impression of relief" work?

Maybe terrian?

**Comment by 4ian** [comment]
Thanks again @Midhil457 for the review and @D8H for the example :) 
I went for "simulate a landscape (with embossed surfaces) from a top-down viewpoint." (we can always adapt it if you have other ideas)

**Pull request merged**
