### PR TITLE
New Break Out Example

### PR DESCRIPTION
**Pull request by Midhil457**
new Break out example 
This hasn't been reviewed in this repo, but has been reviewed in the main repo
Same as: https://github.com/4ian/GDevelop/issues/2629

- [x] Add thumnail.png
- [x] Add a README (same as the old example)
- [x] Increment version number (now 2.0.0)

Now as I am thinking about it, I should have probably made an issue instead of a PR, sorry 😓 

:)

### CODE REVIEW

**Comment by Midhil457** [comment]
Why did image actions skip? There are a lot of images, so compressing them might be important

**Comment by 4ian** [comment]
It's not running for safety measure because your branch is in a fork, but there will be a daily automatic PR compressing them creating after we merge this.

**Comment by Bouh** [comment]
I checking this example today!

**Review by Bouh — APPROVED** [review]

**Comment by Bouh** [comment]
Thank you @Midhil457 for this huge rework on the breakout example!

**Pull request merged**
