### PR TITLE
Add infinitely scrolling top down example by Mixen-me

### LINKED ISSUE #158: Example of how you can make the background move infinitely as the camera moves.
## Example of how you can make the background move infinitely as the camera moves.

This example is a showcase of how you can make a background that moves infinitely as the camera moves but stops moving if the camera stop.

## Checklist

- [x] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example).
- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated into this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

## Game folder
[InfiniteBackgroundLoop.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7834482/InfiniteBackgroundLoop.zip)

### PR DESCRIPTION
**Pull request by Midhil457**
Not going to immediately push this as I am worried about the long project name. `top-down` had to be added as there is already an example that shows infinite scrolling BG (but it's a platformer). Any suggestions?

closes #158

### CODE REVIEW

**Comment by Bouh** [comment]
> Not going to immediately push this as I am worried about the long project name. `top-down` had to be added as there is already an example that shows infinite scrolling BG (but it's a platformer). Any suggestions?

I'm worried too, this example adds the same action that the existing example `infinite-scrolling-background.json`.
I suggest adding in the existing example another scene with the content of this PR and updating the Readme with the addition.

**Comment by Bouh** [comment]
In the first comment of the example:

> y is the Position after which the Sprite starts looping again. In this case, I multiplied the Width and Height of the Project by 2 and wrote it.

It should not be necessary to explain this simple calculation...
The expression is preferable to a calculated value.

> Note: The size of the Tile is 5x larger than scene's resolution and is evenly distributed in each side in relative to the centre of screen.

Why 5x ? 

@Mixen-me

**Comment by kursatnacar27** [comment]
okey

**Comment by Bouh** [comment]
I just merged this new example by adding it to the current example for background scrolling.
So now there are two scenes in the example with two different methods.

**Pull request merged**
