### PR TITLE
The Conviction of Gun Dude (desktop version)

### PR DESCRIPTION
**Pull request by tristanbob**
- Initial import from #291 
- Removed unused objects from StartScene
- Cleaned up events in StartScene

### CODE REVIEW

**Comment by HelperWesley** [comment]
Got this version from github desktop app, but I wasn't sure how to send it, so sending it as a zip. 😅

[conviction-of-gun-dude-desktop.zip](https://github.com/GDevelopApp/GDevelop-examples/files/8800893/conviction-of-gun-dude-desktop.zip)

-Deleted extra condition for upgrades
image

-Changed the gun image so it more accurately aims toward the mouse.

-Used the wait action in the countdown event in start scene and game reset.
image

-Added a comment above the leaderboard event to explain why it's there.
image

-Added to the comment above the health bar event to explain the 216 number.
image

-Changed "magic values" to the room height and width expressions.
image

-Added description to the game in project manager.

-Moved everything to an asset folder with sub folder for audio, fonts, and marketing material.(icons and thumbnails)

-Removed darkening object from start scene.

-Added a very basic pause menu. While paused you can see the controls on screen, and if you hover over an upgrade icon it will tell you what the upgrade does.

-And added trigger once to the flip player event.
image

**Comment by HelperWesley** [comment]
I'll create a separate mobile version based off of this one once we've confirmed this one passes, so I'm not applying changes to each version. 👍

I definitely think there need to be two versions, for the benefit of both versions. If we did just 1 version, 1 side of the game would be inferior and not useful for people to work from.

**Comment by HelperWesley** [comment]
https://github.com/HelperWesley/GDevelop-examples/tree/TheConvictionOfGunDude_Desktop

I also pushed my commits to my fork, if you prefer to access it that way.

**Comment by Bouh** [comment]
Could you send us the latest version you use? 
Or take a few minutes to merge your changes here, it's all the concept of Git to be able to work with one workflow in one Pull Request ^^

**Review by Bouh — APPROVED** [review]

**Pull request merged**
